---
title: "Module04_Workshop03"
author: "Laura Schofield"
date: "2025-04-09"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
```

## To download data go to:

https://qfish.fisheries.qld.gov.au/query/number-caught-by-area-calendar-year-and-species-group/table 

# Load data

```{r}
QFish <-
  read.csv("../data/QFish.csv") |>
  row_to_names(row_number = 2, remove_rows_above = FALSE) |>
  clean_names()

head(QFish)
```


Subset shark data
```{r}
shark_catch <- QFish |>
  select (1 | contains("shark")) |>
  row_to_names(row_number = 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))
```

Check
```{r}
shark_catch
```

Make into long df
```{r}
shark_catch_long <- 
shark_catch |>
  pivot_longer(!Area, names_to = "Year", values_to = "Nos") |>
  mutate(across(-c(Area), as.numeric))


```

Check
```{r}
shark_catch_long
```

Making a pivot table
```{r}
shark_catch_long<- 
shark_catch |>
  pivot_longer(!Area, names_to = "Year", values_to = "Nos")
```

Make stats tibbles
```{r}
shark_stats <- 
shark_catch_long |>
  filter(Area != "Grand Total") |>
  group_by(Year) |>
  summarise(Mean = mean(Nos, na.rm = TRUE),
            SD = sd(Nos, na.rm = TRUE)) |>
  mutate(Year = as.numeric(Year)) |>
  mutate(Taxa = "Sharks")
```

Graph
```{r}
ggplot(data = shark_stats, aes(x = Year, y = Mean, fill = Taxa, shape = Taxa)) +
  geom_line(aes(group = Taxa), colour = "black") +
  geom_pointrange(aes(ymin = Mean - SD, ymax = Mean + SD), colour = "black") +
  scale_shape_manual(values = c(23, 24))
```



